### ISSUE TITLE
Finetuning on custom dataset

### ISSUE THREAD

**Issue by o0t1ng0o** [kyegomez/CM3Leon#1]
Hi @kyegomez, 
Thank you for sharing this code.
Could you give an example to finetune on the custom dataset for image caption or text2image tasks?

Thanks!

**Comment by BURJAMANISHA** [comment]
Yes , please could you provide us with one example on how to fine tune it on custom dataset

**Comment by kyegomez** [comment]
@o0t1ng0o @BURJAMANISHA Hello, first you need tokenizer, to tokenize text and images then pass inputs to the model then train the model and then finetune. The first step is getting tokenizer
