### ISSUE TITLE
zeta library does not compile

### ISSUE THREAD

**Issue by m0zzaR** [kyegomez/CM3Leon#10]
These two lines in model.py do not compile for me. I have already pip installed cm3.

from zeta.nn.architecture.auto_regressive_wrapper import AutoregressiveWrapper
from zeta.nn.architecture.transformer import (

**Comment by jybxie123** [comment]
I have the same problem, installed the cm3 by the instruction in the Readme.

**Comment by kyegomez** [comment]
@jybxie123 @m0zzaR please upgrade zeta with 'pip install --upgrade zetascale'
