### ISSUE TITLE
Is CM3Leon not gonna be open source?

### ISSUE THREAD

**Issue by BoghosDavtyan** [kyegomez/CM3Leon#2]

**Comment by kyegomez** [comment]
Hey @BoghosDavtyan  Nope it isn't. Unfortunately it's up to us to implement it

**Comment by m0zzaR** [comment]
@kyegomez What do you mean by "implement it". How are we supposed to implement something that we don't have access too?

**Comment by rsxdalv** [comment]
> @kyegomez What do you mean by "implement it". How are we supposed to implement something that we don't have access too?

Based on the research paper which we do have access to.

**Comment by Al-aminI** [comment]
yeah of course, there is quite a detail that we can use to implement it, this is great.

 but why are you using ViT to encode the images, from the original CM3leon paper, they used VQGAN to tokenize the images. and i didn't see where you are using the tokenizer you build in the in the cm3 directory.

i will like to contribute, but there are some things that i didn't understand actually. 
it seems the train.py is not tested.

**Comment by kyegomez** [comment]
@Al-aminI Your right they do used VQGAN as an encoder, but I just used a vit for simplicity. I'm very open minded to refactoring this to use VQGAN if you can help me
