### ISSUE TITLE
Error while processing rearrange-reduction pattern

### ISSUE THREAD

**Issue by rsxdalv** [kyegomez/CM3Leon#6]
Code:
```python
import torch
from cm3.model import CM3

model = CM3(
    depth=24, dim=1536
)
model_gpu = model.to('cuda:0')

img = torch.randn(1, 3, 256, 256)
text = torch.randint(0, 20000, (1, 1024))
output2 = model_gpu(text, img)
```
Error:
Failed in forward method:  Error while processing rearrange-reduction pattern "b c (h p1) (w p2) -> b (h w) (p1 p2 c)".
 Input tensor shape: torch.Size([1, 1024]). Additional info: {'p1': 32, 'p2': 32}.
 Expected 4 dimensions, got 2
---------------------------------------------------------------------------
EinopsError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/einops/einops.py](https://localhost:8080/#) in reduce(tensor, pattern, reduction, **axes_lengths)
    411         recipe = _prepare_transformation_recipe(pattern, reduction, axes_lengths=hashable_axes_lengths)
--> 412         return _apply_recipe(recipe, tensor, reduction_type=reduction)
    413     except EinopsError as e:

8 frames
EinopsError: Expected 4 dimensions, got 2

During handling of the above exception, another exception occurred:

EinopsError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/einops/einops.py](https://localhost:8080/#) in reduce(tensor, pattern, reduction, **axes_lengths)
    418             message += '\n Input is list. '
    419         message += 'Additional info: {}.'.format(axes_lengths)
--> 420         raise EinopsError(message + '\n {}'.format(e))
    421 
    422 

EinopsError:  Error while processing rearrange-reduction pattern "b c (h p1) (w p2) -> b (h w) (p1 p2 c)".
 Input tensor shape: torch.Size([1, 1024]). Additional info: {'p1': 32, 'p2': 32}.
 Expected 4 dimensions, got 2

**Comment by kyegomez** [comment]
@rsxdalv your supposed to place the 4d image inputs as input first in cm3, so like cm3(img, test)
