### ISSUE TITLE
What is the output of the model?

### ISSUE THREAD

**Issue by ChaerinMin** [kyegomez/CM3Leon#9]
In the example.py file, the model output should be of shape `print(output[0].shape) # (1, 1024, 20000). `
What is this (1,1024,20000) matrix? I thought the CM3Leon model is an image generator, but (1,1024,20000) doesn't seem like an image. 
Thank you for your great work and I'm looking forward to hearing from you.

**Comment by kyegomez** [comment]
@ChaerinMin the models output are supposed to be conditional, using the contrastive topk method in the paper they're trying to get conditional image generation should the model decide the user wants to generate an image

**Comment by kyegomez** [comment]
@ChaerinMin please check my implementation of topk decoding and improve it so we can finish this implementation
